version: '3'
services:
    servant-persistent:
        build: .
        image: servant-persistent
        command: servant-persistent
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - servant-persistent
